export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILED = 'GET_POKEMONS_FAILED';
export const GET_POKEMONS_PENDING = 'GET_POKEMONS_PENDING';

export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS';
export const SEARCH_POKEMON_FAILED = 'SEARCH_POKEMON_FAILED';
export const SEARCH_POKEMON_PENDING = 'SEARCH_POKEMON_PENDING';

export const GET_POKEMON = 'GET_POKEMON';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILED = 'GET_POKEMON_FAILED';
export const GET_POKEMON_PENDING = 'GET_POKEMON_PENDING';
