export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILED = 'GET_POKEMONS_FAILED';
export const GET_POKEMONS_PENDING = 'GET_POKEMONS_PENDING';
